Repository ManageIQ/manageiq-providers-oracle_cloud, pull requests merged in 2021-03, with the labels that each got.

#4 Add initial EmsRefresh for Oracle Cloud
  app/models/manageiq/providers/oracle_cloud/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister/definitions/cloud_collections.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/oracle_cloud/cloud_manager/refresher.yml
Labels: enhancement

#5 Move default vcr secrets to config/secrets.default.yml
  .codeclimate.yml
  .gitignore
  config/secrets.defaults.yml
  lib/manageiq/providers/oracle_cloud/engine.rb
  spec/factories/ext_management_system.rb
  spec/spec_helper.rb
Labels: refactoring, test

#7 Combined refresh for Cloud/Network Managers
  app/models/manageiq/providers/oracle_cloud/inventory/collector.rb
  app/models/manageiq/providers/oracle_cloud/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/inventory/collector/network_manager.rb
  app/models/manageiq/providers/oracle_cloud/inventory/parser.rb
  app/models/manageiq/providers/oracle_cloud/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/inventory/parser/network_manager.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister/network_manager.rb
Labels: enhancement, performance

#6 Collect network manager inventory
  app/models/manageiq/providers/oracle_cloud/inventory/collector.rb
  app/models/manageiq/providers/oracle_cloud/inventory/parser.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/oracle_cloud/cloud_manager/refresher.yml
Labels: enhancement

#8 Collect CloudVolumes and AvailabilityZones
  app/models/manageiq/providers/oracle_cloud/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/availability_zone.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/cloud_volume.rb
  app/models/manageiq/providers/oracle_cloud/inventory/collector.rb
  app/models/manageiq/providers/oracle_cloud/inventory/parser.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/oracle_cloud/cloud_manager/refresher.yml
Labels: enhancement

#9 Fix raw_connect param order in verify_credentials
  app/models/manageiq/providers/oracle_cloud/manager_mixin.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager_spec.rb
  spec/vcr_cassettes/manageiq/providers/oracle_cloud/cloud_manager.yml
Labels: bug

#11 Simplify running refresher_spec with local secrets
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/refresher_spec.rb
Labels: test

#13 Add event catcher for Oracle Cloud
  app/models/manageiq/providers/oracle_cloud/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/event_catcher/runner.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/event_catcher/stream.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/event_parser.rb
  app/models/manageiq/providers/oracle_cloud/manager_mixin.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/event_parser_spec.rb
Labels: enhancement

#15 Fix public-key text area component
  app/models/manageiq/providers/oracle_cloud/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/manager_mixin.rb
Labels: bug

#12 Use combined manager refresh support from core
  app/models/manageiq/providers/oracle_cloud/inventory/persister.rb
Labels: refactoring

#17 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#14 Add targeted refresh for Oracle Cloud
  app/models/manageiq/providers/oracle_cloud/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/event_parser.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/event_target_parser.rb
  app/models/manageiq/providers/oracle_cloud/inventory.rb
  app/models/manageiq/providers/oracle_cloud/inventory/collector.rb
  app/models/manageiq/providers/oracle_cloud/inventory/collector/target_collection.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister/target_collection.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/oracle_cloud/cloud_manager/refresher_vm_target.yml
Labels: enhancement

#18 Metrics Capture for Oracle Cloud
  app/models/manageiq/providers/oracle_cloud/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/metrics_collector_worker.rb
  spec/factories/vm_or_template.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/metrics_capture_spec.rb
  spec/vcr_cassettes/manageiq/providers/oracle_cloud/cloud_manager/metrics_capture.yml
Labels: enhancement

#19 Remove some leftover code from original repo
  app/models/manageiq/providers/oracle_cloud/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/auth_key_pair.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/provision.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/provision_workflow.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/template.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/vm.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/vm/operations/guest.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/vm/operations/power.rb
  app/models/manageiq/providers/oracle_cloud/network_manager/network_port.rb
  app/models/manageiq/providers/oracle_cloud/network_manager/refresh_parser.rb
  app/models/manageiq/providers/oracle_cloud/refresh_helper_methods.rb
Labels: cleanup

#16 Add blacklisted event filtering support
  app/models/manageiq/providers/oracle_cloud/cloud_manager/event_catcher/runner.rb
  config/settings.yml
Labels: enhancement
