Repository ManageIQ/manageiq-providers-oracle_cloud, pull requests merged in 2022-01, with the labels that each got.

#39 Don't subclass ContainerVolume
  app/models/manageiq/providers/oracle_cloud/container_manager.rb
  app/models/manageiq/providers/oracle_cloud/container_manager/container_volume.rb
Labels: bug

#41 The identity service's URL has changed in the latest gem version
  manageiq-providers-oracle_cloud.gemspec
  spec/vcr_cassettes/manageiq/providers/oracle_cloud/cloud_manager.yml
  spec/vcr_cassettes/manageiq/providers/oracle_cloud/cloud_manager/refresher.yml
Labels: bug, morphy/yes?

#42 Add whitesource config
  .whitesource
Labels: test

#44 Fix whitesource config files
  .whitesource
Labels: cleanup
