Repository ManageIQ/manageiq-providers-oracle_cloud, pull requests merged in 2022-05, with the labels that each got.

#55 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: developer, test

#57 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#60 Create cloud databases support
  app/models/manageiq/providers/oracle_cloud/cloud_manager/cloud_database.rb
  spec/factories/cloud_database.rb
  spec/factories/cloud_subnet.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/cloud_database_spec.rb
Labels: enhancement

#61 Delete cloud database support
  app/models/manageiq/providers/oracle_cloud/cloud_manager/cloud_database.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/cloud_database_spec.rb
Labels: enhancement

#62 Set OCI.logger and log to log/oracle.log
  .rubocop_local.yml
  app/models/manageiq/providers/oracle_cloud/oci_connect_mixin.rb
  config/settings.yml
  lib/manageiq/providers/oracle_cloud/engine.rb
Labels: enhancement

#63 Update cloud databases support
  app/models/manageiq/providers/oracle_cloud/cloud_manager/cloud_database.rb
  spec/models/manageiq/providers/oracle_cloud/cloud_manager/cloud_database_spec.rb
Labels: enhancement

#65 Add proxy support for oracle cloud
  app/models/manageiq/providers/oracle_cloud/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/oci_connect_mixin.rb
Labels: morphy/yes?, najdorf/yes?
