Repository ManageIQ/manageiq-providers-oracle_cloud, pull requests merged in 2024-02, with the labels that each got.

#95 Drop require_nested
  app/models/manageiq/providers/oracle_cloud/cloud_manager.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/oracle_cloud/cloud_manager/refresh_worker.rb
  app/models/manageiq/providers/oracle_cloud/container_manager.rb
  app/models/manageiq/providers/oracle_cloud/container_manager/event_catcher.rb
  app/models/manageiq/providers/oracle_cloud/container_manager/refresh_worker.rb
  app/models/manageiq/providers/oracle_cloud/inventory.rb
  app/models/manageiq/providers/oracle_cloud/inventory/collector.rb
  app/models/manageiq/providers/oracle_cloud/inventory/collector/container_manager.rb
  app/models/manageiq/providers/oracle_cloud/inventory/parser.rb
  app/models/manageiq/providers/oracle_cloud/inventory/parser/container_manager.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister.rb
  app/models/manageiq/providers/oracle_cloud/inventory/persister/container_manager.rb
  app/models/manageiq/providers/oracle_cloud/network_manager.rb
Labels: technical debt, rails7

#97 drop use of unsupported_reason_add
  app/models/manageiq/providers/oracle_cloud/cloud_manager/vm.rb
Labels: refactoring

#98 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
